---
format: 
  revealjs:
    width: 1280
    height: 720
preload-iframes: true
---

# {background-iframe="colored-particles/index.html"}

::: r-fit-text
Having fun with
:::

::: r-fit-text
iFrames
:::

```{r}
source("zip-all-the-things.R")
```

## Why should I use iFrames?

In [Quarto Presentations](https://quarto.org/docs/presentations/revealjs/) one way to add something extra is to use [Slide Backgrounds](https://quarto.org/docs/presentations/revealjs/#slide-backgrounds)

Images and videos are good for some added flair, and they automatically fill the background

Using html elements and javascript to make an animated background, is almost impossible to get right inside your `.qmd` file, but super easy with [iFrame Backgrounds](https://quarto.org/docs/presentations/revealjs/#iframe-backgrounds)

## How to use iFrame Backgrounds

1. Add a folder next to your `.qmd` file
2. In that folder add the following files
    - `index.html`
    - `script.js` (optional)
    - `style.css` (optional)
3. Use the following notation to use (title can be empty)

::: {style="font-family: monospace;"}
\# title {background-iframe="my-iframe/index.html"}
:::

4. Set `preload-iframes: true` in yaml

## Folder Structures

This is my preferred setup for a quarto presentation. 

Naming the main file `index.qmd` gives you `index.html` as your output which is a good default for publishing

::: {style="font-family: monospace;"}
awesome-presentation/\
├── index.qmd\
├── index.html\
├── style.scss (only styles index.qmd)\
└── my-iframe/\
\ \  \ ├── index.html\
\ \  \ ├── script.js\
\ \  \ └── style.css (only styles iframe)\
:::

# How to make your own

From [codepen.io](https://codepen.io)

-   find one you like
-   click `export -> export .zip`
-   Copy over the results from the `dist` folder
-   trim and modify content to your liking
-   Add a README file with references
-   Copy over license

## https://particles.js.org/

particles.js is a great library that works perfectly as iFrames, and have amazing customization

::: columns
::: {.column width="50%"}
<iframe src="polygon-mask/index.html" style="width: 100%; aspect-ratio: 1.2;"></iframe>
:::

::: {.column width="50%"}
<iframe src="colored-particles/index.html" style="width: 100%; aspect-ratio: 1.2;"></iframe>
:::
:::

## Gallery

The following slides contain a number of different iframe for you to use, modify and expand on

Clicking the download link should give you a folder with everything you need

Additional entries are welcome at [EmilHvitfeldt/quarto-iframe-examples](https://github.com/EmilHvitfeldt/quarto-iframe-examples)

#  {background-iframe="rotating-earth/index.html"}

::: {style="background-color: #ffffffbb; border-radius: 10px; padding: 5px;"}
::: r-fit-text
Rotating Earth
:::

[Download template](rotating-earth.zip)
:::

#  {background-iframe="hello-matrix/index.html"}

::: {style="background-color: #ffffffbb; border-radius: 10px; padding: 5px;"}
::: r-fit-text
Hello Matrix
:::

[Download template](hello-matrix.zip)
:::

#  {background-iframe="ambient/index.html"}

::: {style="background-color: #ffffff33; border-radius: 10px; padding: 5px;"}
::: r-fit-text
Ambient
:::

[Download template](ambient.zip)
:::

#  {background-iframe="glittering-sea/index.html"}

::: {style="background-color: #ffffffbb; border-radius: 10px; padding: 5px;"}
::: r-fit-text
Glittering Sea
:::

[Download template](glittering-sea.zip)
:::

#  {background-iframe="moving-waves/index.html"}

::: {style="background-color: #ffffffbb; border-radius: 10px; padding: 5px;"}
::: r-fit-text
Moving Waves
:::

[Download template](moving-waves.zip)
:::

#  {background-iframe="grid-worms/index.html"}

::: {style="background-color: #ffffffbb; border-radius: 10px; padding: 5px;"}
::: r-fit-text
Grid Worms
:::

[Download template](grid-worms.zip)
:::

#  {background-iframe="meatballs/index.html"}

::: {style="background-color: #ffffffbb; border-radius: 10px; padding: 5px;"}
::: r-fit-text
Meatballs
:::

[Download template](meatballs.zip)
:::

#  {background-iframe="tetris/index.html"}

::: {style="background-color: #ffffffbb; border-radius: 10px; padding: 5px;"}
::: r-fit-text
tetris
:::

[Download template](tetris.zip)
:::

#  {background-iframe="boids/index.html"}

::: {style="background-color: #ffffffbb; border-radius: 10px; padding: 5px;"}
::: r-fit-text
boids
:::

[Download template](boids.zip)
:::

#  {background-iframe="multiple-images/index.html"}

::: {style="background-color: #ffffffbb; border-radius: 10px; padding: 5px;"}
::: r-fit-text
Multiple Floating Images
:::

[Download template](multiple-images.zip)
:::

#  {background-iframe="polygon-mask/index.html"}

::: {style="background-color: #ffffff33; border-radius: 10px; padding: 5px;"}
::: r-fit-text
Polygon Mask
:::

[Download template](polygon-mask.zip)
:::

#  {background-iframe="colored-particles/index.html"}

::: {style="background-color: #ffffffbb; border-radius: 10px; padding: 5px;"}
::: r-fit-text
Colored Particles
:::

[Download template](colored-particles.zip)
:::

#  {background-iframe="logo-fall/index.html"}

::: {style="background-color: #ffffffbb; border-radius: 10px; padding: 5px;"}
::: r-fit-text
Logo Fall
:::

[Download template](logo-fall.zip)
:::
